"""
Shared state for the Hello World self-correction agent.

The state travels through every node in the graph.
LangGraph merges each node's return value (partial dict) into
the running snapshot — only the keys a node changes need to be returned.
"""
from typing import Annotated
from typing_extensions import TypedDict


class HelloWorldState(TypedDict):
    # The task the user gave the agent (e.g. "Write a Hello World program in Python")
    task: str

    # The most recent code/text generated by the LLM
    result: str

    # Feedback produced by the validator node ("" means the result is acceptable)
    feedback: str

    # How many generation attempts have been made (guards against infinite loops)
    attempt_count: Annotated[int, "incremented by generate_node on each call"]

    # Maximum allowed attempts before the graph gives up
    max_attempts: int
